# Generated by Django 2.2.6 on 2020-09-23 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexEntry',
            options={'verbose_name_plural': 'Index Entries'},
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=255)),
                ('block_type', models.IntegerField(choices=[(0, 'Other'), (1, 'Struct'), (2, 'Stream')])),
                ('block_value', models.TextField(blank=True)),
                ('block_path', models.TextField()),
                ('field_name', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page')),
            ],
        ),
    ]
